### ISSUE TITLE
Moving to Placemarker now Very Slow

### ISSUE THREAD

**Issue by dan1982code** [nvdaes/placeMarkers#13] opened 2018-12-08 21:04 UTC
Hi. I don't exactly know when this happened, but in NVDA 2018.4 and now NVDA 2019.1 alpha, with PlaceMarkers 12.1, moving to a placemarker in Firefox and/or Chrome is very slow. For example, I have a 1mb text file (textbook) open in Firefox. Setting the temporary placemarker is immediate. Moving to it, however, takes over 30 seconds, when it used to be immediate.

**Comment by nvdaes** [comment] 2018-12-08 21:48
Hello: Thanks for your interest. I will take care of this, but I can reproduce this issue for now using placeMarkers 12.1 and NVDA 2019.1 (alpha).
Hope we can find what's causing this for fixing it ASAP.

**Comment by dan1982code** [comment] 2018-12-08 23:52
Thank you! Please let me know if I can help test. Fast placemarkers is a key feature for me. It seems related to the location of the placemarker; i.e. it takes longer to move to a placemarker that's very far into a large document. Thank you as always for this addon.

**Comment by dan1982code** [comment] 2018-12-18 17:49
I can reproduce this again using PlaceMarkers 12.2 and NVDA 2019.1 alpha.

Do you have any leads? May I help somehow (testing old versions of things and reporting back)?

**Comment by nvdaes** [comment] 2018-12-18 17:56
Yes please. Test and report feedback. Also, you can provida a webpage or document so I can test too, with different browsers.

**Comment by dan1982code** [comment] 2018-12-18 22:40
Testing: it happens in NVDA 2019.1 alpha with all virtual buffers: Firefox, Chrome, and Internet Explorer (have not tested Edge). To reproduce, load any large text file (e.g. one megabyte or greater), and set a temporary placemarker close to the end. Then, go to the top and try to move to the temporary marker. It will take a minute or more.

**Comment by nvdaes** [comment] 2018-12-19 09:41
Confirmed. At least for now, I don't know how to fix this.
I will investigate and ask in the add-ons mailing list.
This is produced when moving the TextInfo object a lot of characters.
Also, though related issues have been closed by NV Access due to patent concerns, this is an issue where this add-on is mentioned:
https://github.com/nvaccess/nvda/issues/4973
The first related issue is
https://github.com/nvaccess/nvda/issues/88, in case you want to try to reopen it. If bookmarks could be created for browse mode documents as nav items like headings, links, etc., perhaps this may be easier and more efficient than an approach from this add-on.

**Comment by nvdaes** [comment] 2018-12-19 12:33
This doesn't happen in NVDA 2018.4.
I have opened an issue for NVDA at
https://github.com/nvaccess/nvda/issues/9093

**Comment by dan1982code** [comment] 2018-12-30 22:07
Incredible! Version 12.2.1 of PlaceMarkers jumps to place markers immediately, far faster than even in NVDA 2018.4. Thank you!

**Comment by nvdaes** [comment] 2019-08-09 10:54
I should have this closed time ago. Thanks for your valuable comments.

**Closed by nvdaes** 2019-08-09 10:54 UTC
